CURRICULUM_MAP = {
    "420": "Compiler Design",
    "421": "Computer Networks",
    "422": "Artificial Intelligence",
    "423": "Computer Graphics",
    "424": "Pattern Recognition",
    "425": "Neural Networks",
    "427": "Machine Learning",
    "428": "Image Processing",
    "430": "Digital Signal Processing",
    "431": "Natural Language Processing",
    "432": "Speech Recognition",
    "460": "VLSI Design",
    "461": "Robotics",
    "470": "Software Engineering",
    "471": "Systems Analysis and Design",
    "472": "Human Computer Interaction",
    "473": "Financial Engineering",
    "490": "WAN Routing Technologies",
    "310": "Object Oriented Programming",
    "320": "Data Communications",
    "321": "Operating Systems",
    "340": "Computer Architecture",
    "341": "Microprocessors",
    "370": "Database Systems",
    "220": "Data Structures",
    "221": "Algorithms"
}